#+TITLE: Notes on HTML and related things
#+DESCRIPTION: Notes on HTML and related things like CSS etc.

#+HTML_DOCTYPE: html5
#+HTML_LINK_UP: ./index.html
#+HTML_LINK_HOME: ./index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./static/worg.css" />
#+HTML_MATHJAX: path: "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"
#+OPTIONS: html-style:nil
#+OPTIONS: num:nil toc:nil

* Intro
Private notes on HTML and CSS .. etc. \\
Starting from the material [[https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML][provided by Mozilla]]

* HTML
** Opening
An *HTML* file starts with stating which standard it holds to. A minimal example that works is the following
#+BEGIN_SRC html :tangle html-demo.html
<!DOCTYPE html>
#+END_SRC
Next you declare the opening of the document. This wraps all the content
#+BEGIN_SRC html :tangle html-demo.html
<html>
#+END_SRC
** Head
Next we open up the "head" which will contain info about the document - but things that aren't directly visible.\\
Ex:\\
 - The title that will show up at the top (as the tab name for instance)
 - Metadata:
   + The character set used by the webpage 
   + The author
   + Other stuff for OpenGraph/Twitter etc. see: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#Other_types_of_metadata
 - The icon
 - The CSS stylesheet (covered in the latter part of the document)
#+BEGIN_SRC html :tangle html-demo.html
  <head>
    <title>My test page</title>
    <meta charset="utf-8">
    <meta name="author" content="George Kontsevich">
    <meta name="description" content="This is a dummy description for a test page
				      that I've made to remind myself of HTML stuff">
    <link rel="shortcut icon" href="gk.ico" type="image/x-icon">
    <link rel="stylesheet" href="css-demo.css">
#+END_SRC

#+BEGIN_SRC html :tangle html-demo.html
  </head>
#+END_SRC
** Body
Now we have the stuff that ends up displaying on the page
#+BEGIN_SRC html :tangle html-demo.html
    <body>
      <h1> This is an h1 (top level) header - usuall one per page </h1>
#+END_SRC
*** Text formating
#+BEGIN_SRC html :tangle html-demo.html
  <p>This is a paragraph</p>
  <ul>
    <li>unordered</li>
    <li>list</li>
    <li>of</li>
    <li>words</li>
  </ul>
  <ol>
    <li>ordered</li>
    <li>list</li>
    <li>of</li>
    <li>words</li>
    <ul>
      <li>with</li>
      <li>an</li>
      <li>unordered</li>
      <li>list</li>
      <li>of</li>
      <li>words</li>
      <li>inside</li>
    </ul>
  </ol>
  <p>The following is with emphasis: <em>pandas</em></p>
  <p>The following is strong: <strong>more pandas</strong></p>
  <p>Similarly bold (which should be used less b/c it has no semantic meaning): <b>all the pandas</b></p>
  <p>
    Descriptions List:
    <dl>
      <dt>soliloquy</dt>
      <dd>In drama, where a character speaks to themselves, representing their inner thoughts or feelings and in the process relaying them to the audience (but not to other characters.)</dd>
      <dt>monologue</dt>
      <dd>In drama, where a character speaks their thoughts out loud to share them with the audience and any other characters present.</dd>
      <dt>aside</dt>
      <dd>In drama, where a character shares a comment only with the audience for humorous or dramatic effect. This is usually a feeling, thought, or piece of additional background information.</dd>
    </dl>
  </p>
  <p>The quote element — <code>&lt;q&gt;</code> — is <q cite="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/q">intended
      for short quotations that don't require paragraph breaks.</q></p>
  <blockquote cite="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote">
    <p>The <strong>HTML <code>&lt;blockquote&gt;</code> Element</strong> (or <em>HTML Block
	Quotation Element</em>) indicates that the enclosed text is an extended quotation.</p>
  </blockquote>
  <p>We use <abbr title="Hypertext Markup Language">HTML</abbr> to structure our web documents.</p>

  <p>I think <abbr title="Reverend">Rev.</abbr> Green did it in the kitchen with the chainsaw.</p>
  <p>Caffeine's chemical formula is C<sub>8</sub>H<sub>10</sub>N<sub>4</sub>O<sub>2</sub>.</p>
<pre><code>var para = document.querySelector('p');

para.onclick = function() {
  alert('Owww, stop poking me!');
}</code></pre>

<p>You shouldn't use presentational elements like <code>&lt;font&gt;</code> and <code>&lt;center&gt;</code>.</p>

<p>In the above JavaScript example, <var>para</var> represents a paragraph element.</p>


<p>Select all the text with <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>A</kbd>.</p>

<pre>$ <kbd>ping mozilla.org</kbd>
<samp>PING mozilla.org (63.245.215.20): 56 data bytes
64 bytes from 63.245.215.20: icmp_seq=0 ttl=40 time=158.233 ms</samp></pre>

#+END_SRC
*** Links
In the following example we wrap some text with a hyperlink
#+BEGIN_SRC html :tangle html-demo.html
  <p>Now we want to create to my github
    <a href="https://github.com/geokon-gh/"
       title="This is the mouseover text! :)">My Github (with special mouse over text!)</a>
  </p>
#+END_SRC
However you can also wrap images and other elements\\
As well as link to IDs (once set)
#+BEGIN_SRC html :tangle html-demo.html
<h2 id="Mailing_address">Mailing address</h2>
<p>Want to write us a letter? Use our <a href="html-demo.html#Mailing_address">mailing address</a>.</p>
#+END_SRC
You can also set default download names. For instance this is a link to the latest Firefox:
#+BEGIN_SRC html :tangle html-demo.html
<p>
<a href="https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US"
   download="some-silly-default-file-name.exe">
  Download Latest Firefox for Windows (64-bit) (English, US)
</a>
</p>
#+END_SRC
Or link to emails
#+BEGIN_SRC html :tangle html-demo.html
<p>
<a href="mailto:nowhere@mozilla.org?cc=name2@rapidtables.com&bcc=name3@rapidtables.com&subject=The%20subject%20of%20the%20email&body=The%20body%20of%20the%20email">
  Send mail with cc, bcc, subject and body
</a>
</p>
#+END_SRC
*** Images
The ~<figure>~ wrapper ~<figcaption>~ elements are for *HTML5* and allow for captions with an element that has the appropriate semantic meaning (I've doubled the icon's actual width and height)
#+BEGIN_SRC html :tangle html-demo.html
<figure>
  <img src="gk.ico"
       alt="This is text that displays if the image doesn't load"
       width="94"
       height="112"
       title="This is some mouse-over text">

  <figcaption>This is the caption below the icon image.</figcaption>
</figure>
#+END_SRC
*** Video/Audio
Just a small basic example (205kB file). For more details see: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content
#+BEGIN_SRC html :tangle html-demo.html
<video src="pregnant-shrimp.webm" controls>
  <p>Your browser doesn't support HTML5 video. Here is a <a href="pregnant-shrimp.webm">link to the video</a> instead.</p> 
</video>
#+END_SRC

*** iframes
Are used to embed other webpages into the current page
#+BEGIN_SRC html :tangle html-demo.html
<p> Below is an iframe 200 pix high </p>
<iframe src="index.html"
        width="100%" height="200" frameborder="0"
        allowfullscreen sandbox>
  <p> <a href="https://geokon-gh.github.io/index.html"
    Fallback link for browsers that don't support iframes
  </a> </p>
</iframe>
#+END_SRC

** Closing stuff
Gotta close some of the outer brackets
#+BEGIN_SRC html :tangle html-demo.html
  </body>
</html>
#+END_SRC

* CSS
** Rules
Or /ruleset/. Each /rule/ is a paired *selector* and a *declaration block*
*** Selector
Is a pattern that matches some element on a page
#+BEGIN_SRC css :tangle css-demo.css
h1
#+END_SRC
*** Declaration Block
Is a series of declaration - each a pair of a /property/ and a /value/
#+BEGIN_SRC css :tangle css-demo.css
  {
  color: red;
  background-color: grey;
  border: 1px solid black;
  }
#+END_SRC
** Statements
Are additional blocks that can be written in CSS. The most common are /at-rules/ which sometimes can be /nested/
#+BEGIN_SRC css :tangle css-demo.css
@media (min-width: 801px) {
  body {
    margin: 0 auto;
    width: 800px;
  }
}
#+END_SRC
